### ISSUE TITLE
The paper's code seems not being here

### ISSUE THREAD

**Issue by AriaTZY** [MarkMoHR/virtual_sketching#1]
Hello,

I just have read your paper and got so interested in this project, but when I followed the link to this github page, it seems like there is no implementation code here. Could I ask will they be upload in the further and when?

Thank you very much!
Tan

**Comment by MarkMoHR** [comment]
Thank you for the interest in this work!

We will organize the code and release them together with the trained models, as soon as possible after our preparation for all the presentation videos for the SIGGRAPH conference (deadline on 4th June).

:)

**Comment by KTRosenberg** [comment]
I'm looking forward to trying this! Once you have the code organized, will you also include instructions for device setup, installation, and so on?
Thanks!

**Comment by MarkMoHR** [comment]
Hi, I have released the code and the trained models.

Please let me know if you meet any problem or there is any issue.
