### ISSUE TITLE
预测结果难以复现，请问是需要做什么设置吗

### ISSUE THREAD

**Issue by fyqgit** [MarkMoHR/virtual_sketching#11]
你好，跑出来的结果大多数空白的，少数有一些点，请问是哪里需要设置吗？

**Comment by MarkMoHR** [comment]
你好哈，理论上按照readme的步骤就好了，不需要额外的设置。你有没有试过使用sample_inputs文件夹里面的图像测试？如果sample_inputs里面可以跑出正常结果，你自己的数据还是出现你说的问题，那可能就是你的输入数据有问题了（比如线条宽度、灰度值等）。

**Comment by fyqgit** [comment]
感谢您的回复，我使用的就是sample_inputs里面的图片做的测试，线条向量化、线条简化和人脸线条化都做了尝试，sample参数设置50，生成50张也都是类似的结果。看到您说明了需要多做些测试从中选取优秀的生成结果，请问您大概是多少次实验能得到相对较好的结果呢？还有您在测试时有经常出现空白或者少数点点的情况吗？
![output](https://user-images.githubusercontent.com/26499520/218978394-10ba3bcc-065a-42d3-881d-fec680b7d47e.png)

**Comment by MarkMoHR** [comment]
你好，你现在跑出来的结果是不正常的。我说的“选取优秀的生成结果”，是指生成的都是正常结果，然后挑最优。你看看是否没有把预训练模型读进去？或者有没有正确下载？

**Comment by fyqgit** [comment]
好滴，再次感谢您，应该是我这的问题，我再试一下！

**Comment by panda7777777** [comment]
请问是否解决了呢？我也遇到了相同的问题。
![muten_0_pred](https://github.com/MarkMoHR/virtual_sketching/assets/97934971/bde01330-24d9-4cba-8840-541aba90ff10)

**Comment by MarkMoHR** [comment]
看着像没有把模型读进去，可以检查一下代码~

**Comment by panda7777777** [comment]
> 看着像没有把模型读进去，可以检查一下代码~

好滴，感谢您的回复！

**Comment by panda7777777** [comment]
找到问题所在了，我之前testing用的是一张4090的机器，没有第二张显卡，换成实验室多卡机器，问题就解决了，可以跑出很不错的结果！

**Comment by panda7777777** [comment]
另外单张显卡不修改代码也是无法训练的，程序会自动寻找第二张显卡
