### ISSUE TITLE
Questions of the loss weight reg

### ISSUE THREAD

**Issue by WinKawaks** [MarkMoHR/virtual_sketching#14]
Hi, thank you for the great work. We ran into a small problem. The model always generated sketches with more than 300 strokes. We hope to get sketches with fewer but longer strokes. In the Figure 13 of the main paper, the length of the strokes is highly correlated to the loss weight of reg. But we find only weight 0.1 is released in your trained model. Could you please share models with a larger weight(e.g. 1.0)? Or other solutions to get strokes as long as possible? Many thanks!

**Comment by MarkMoHR** [comment]
Hi, the trained weight with regularization weight 1.0 is uploaded to [https://drive.google.com/drive/folders/1-hi2cl8joZ6oMOp4yvk_hObJGAK6ELHB?usp=sharing](https://drive.google.com/drive/folders/1-hi2cl8joZ6oMOp4yvk_hObJGAK6ELHB?usp=sharing).
