### ISSUE TITLE
关于光标初始位置是否随机选取？

### ISSUE THREAD

**Issue by panda7777777** [MarkMoHR/virtual_sketching#17]
您好！

我们已成功复现了您的工作，并且取得了非常理想的效果。目前，我们正尝试将您的工作应用于我们自己的数据集进行可视化处理。在此过程中，我有一个问题想要咨询您：关于光标的初始位置是否是随机选取的。我注意到您在论文中提到了是 Q_0 随机确定的。

期待您的回复，谢谢！

**Comment by MarkMoHR** [comment]
是的，initial cursor是可以随机选取的

**Comment by panda7777777** [comment]
> 是的，initial cursor是可以随机选取的

好的，谢谢您
