### ISSUE TITLE
Fine tuning on other data

### ISSUE THREAD

**Issue by Vahe1994** [MarkMoHR/virtual_sketching#2]
Hello! Great work!
I was wondering is there a way to fine-tune your pretrained model for vectorization. 
In train_vectorization.py  file, if I'm not mistaken,there is only a cold start  variant of training(I mean, pre-trained clean_vectorization module was not loaded). Training from the without pretrained model was working fine, but when I tried to  load from clean_vectorization_model(by adding `load_checkpoint(sess,model_dir, gen_model_pretrain=True)`) I encountered following error(about architecture missmatching)

> 2 root error(s) found.
> 
>   (0) Invalid argument: tensor_name = Variable_1; expected dtype int32 does not equal original dtype float
> tensor_name = Variable_3; expected dtype float does not equal original dtype int32
>          [[node save_1/RestoreV2 (defined at /opt/anaconda3/envs/virtual_sketching/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
>          [[save_1/RestoreV2/_271]]
>   (1) Invalid argument: tensor_name = Variable_1; expected dtype int32 does not equal original dtype float
> tensor_name = Variable_3; expected dtype float does not equal original dtype int32
>          [[node save_1/RestoreV2 (defined at /opt/anaconda3/envs/virtual_sketching/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
> 0 successful operations.
> 0 derived errors ignored.

> Original stack trace for 'save_1/RestoreV2':
>   File "train_vectorization.py", line 319, in <module>
>     main()
>   File "train_vectorization.py", line 315, in main
>     trainer(model_params)
>   File "train_vectorization.py", line 296, in trainer
>     load_checkpoint(sess, '/logs/snapshot/pretrain_clean_line_drawings', gen_model_pretrain=True)
>   File "/code/virtual_sketching/utils.py", line 51, in load_checkpoint
>     restorer = tf.train.Saver(load_var)
>   File "/opt/anaconda3/envs/virtual_sketching/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 828, in __init__
>     self.build()
>   File "/opt/anaconda3/envs/virtual_sketching/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 840, in build
>     self._build(self._filename, build_save=True, build_restore=True)
>   File "/opt/anaconda3/envs/virtual_sketching/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 878, in _build
>     build_restore=build_restore)
>   File "/opt/anaconda3/envs/virtual_sketching/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 508, in _build_internal
>     restore_sequentially, reshape)
>   File "/opt/anaconda3/envs/virtual_sketching/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 328, in _AddRestoreOps
>     restore_sequentially)
>   File "/opt/anaconda3/envs/virtual_sketching/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 575, in bulk_restore
>     return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
>   File "/opt/anaconda3/envs/virtual_sketching/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_io_ops.py", line 1696, in restore_v2
>     name=name)
>   File "/opt/anaconda3/envs/virtual_sketching/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
>     op_def=op_def)
>   File "/opt/anaconda3/envs/virtual_sketching/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
>     return func(*args, **kwargs)
>   File "/opt/anaconda3/envs/virtual_sketching/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
>     attrs, op_def, compute_device)
>   File "/opt/anaconda3/envs/virtual_sketching/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
>     op_def=op_def)
>   File "/opt/anaconda3/envs/virtual_sketching/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
>     self._traceback = tf_stack.extract_stack()

I figured out that likely the problem was that the class for Virtual_Sketching are different for  training and testing .  From the error logs above it is hard to tell where exactly the problem is. Maybe you already encounter this kind of situation-error. I will be very grateful , if you could suggest some solutions or where to look at or maybe tell the right way to do fine-tuning.

**Comment by MarkMoHR** [comment]
Hi,

I haven't done fine-tuning before. I tried it just and this error did appear.

I figure out this is because the `load_checkpoint(.., gen_model_pretrain=True)` also loads the `tf.Variable(***)` in `model_common_train.py`. They are removed in `model_common_test.py`, so the error doesn't appear. You could print the `load_var` to see all the variables to be loaded when training. I didn't define the `name=` for the `tf.Variable(***)`, so they are named `Variable_x` by default. And because of this, they might be disordered and mismatched.

Generally the variables defined by `tf.Variable(***)` in `model_common_train.py` are not necessarily restored during fine-tuning. So you could get around them when loading the model weights, by adding two lines of code in `load_checkpoint`:
```
if gen_model_pretrain:
	load_var = {var.op.name: var for var in tf.global_variables()
				if 'discriminator' not in var.op.name
				and 'raster_unit' not in var.op.name
				and 'VGG16' not in var.op.name
				and 'beta1' not in var.op.name
				and 'beta2' not in var.op.name
				# and 'global_step' not in var.op.name
				and 'train_op' not in var.op.name
				and 'Variable_' not in var.op.name
				}
```
This should work.

**Comment by Vahe1994** [comment]
Thank you very much! It seems to work.
