### ISSUE TITLE
Setting same init cursors position for all test images

### ISSUE THREAD

**Issue by Hrishikesh2798** [MarkMoHR/virtual_sketching#4]
Hey, can you please tell me how should I set the same initial cursor position for all the images for which I perform vectorization. And does setting the same init cursor results in same stroke data every time?

Thank you.

**Comment by MarkMoHR** [comment]
Hi, I don't think it necessary to set the same initial cursor position for all the images. If you want to do so, you could modify the `gen_init_cursors` function in `dataset_utils.py`.
Setting the same init cursor will result in same stroke data every time for an image.

**Comment by Hrishikesh2798** [comment]
thanks a lot
